name: tests-orders

on: 
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and run unit test
        run: |
          cd ./orders
          npm ci
          npm run test:ci
