name: tests

on: 
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        working-directory: ./ticketing/auth
        run: npm install & npm run test:ci
