name: tests-payments

on: 
  pull_request:
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and run unit test
        run: |
          cd ./payments
          npm ci
          npm run test:ci
